version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ryanlacey00/echoes-backend:latest
    
    ports:
      - "127.0.0.1:4729:4729"
    environment:
      VCPKG_ROOT: /vcpkg # Env vars
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /app/src
        - action: sync+restart
          path: ./CMakeLists.txt
          target: /apps

    command: ["/bin/sh", "-c", "cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake && make && ./ECHOES_BACKEND"] # Corrected command format
    restart: unless-stopped
